KAFKA_BOOTSTRAPSERVERS: localhost:9092


server:
  port: 8091

spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/postgres
    username: postgres
    password: soil
  cloud:
    compatibility-verifier:
      enabled: false

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAPSERVERS}
    properties:
      spring:
        json:
          trusted:
            packages: net.apmoller.crb.telikos.libraries.kafkaconsumer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      topics:
        PRODUCER_DTO_TOPIC: booking_dto_topic
    consumer:
      group-id: reactivekafkaconsumerandproducer
      auto:
        offset:
          reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      max:
        poll:
          records: 1
      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false
        spring.json.value.default.type: "net.apmoller.crb.telikos.libraries.kafkaconsumer.dto.BookingDTO"
      topics:
        CONSUMER_DTO_TOPIC: booking_dto_topic


enableCache: true
redis-config:
  setmax-size: 50
  eviction-type: LRU

PRODUCER_DTO_TOPIC: booking_dto_topic
CONSUMER_DTO_TOPIC: booking_dto_topic



logging:
  level:
    org:
      springframework:
        web: DEBUG
        data:
          r2dbc: DEBUG

  pattern:
    level: "[%thread] [%X{correlationId}] %-5level %logger{36} - %msg%n"


redis:
  ssl: true
  host: 127.0.0.1
  port: 6379
  cache-name: "cache-test"
  cache-ttl: 1
